### ISSUE TITLE
Some questions!

### ISSUE THREAD

**Issue by alexpi** [jeromecoupe/eleventy_datocms#1]
Hello,

I have a couple of questions about your post, if you have the time:

- In your example you use a single data file (blogposts.js) to retrieve content. For bigger sites, we would have multiple such files (for different content types). Do you know if it is redundant to fetch the same Dato endpoint multiple times, and if a better way exists?

- I am building a portfolio site. I have a page containing all projects, and some category pages containing only their relevant projects. Since all these pages contain projects, I use a projects.js data file to fetch all projects from all categories. Do you know if we can send a variable to the GraphQL query, to filter the response? 
I was hoping that Eleventy would allow you to send arguments from the template file to the query, but I don't think this is possible.

**Comment by jeromecoupe** [comment]
Hi there.

1. this ks a sandbox. As such the code in there is not really what I would call production ready. I have to make it private I think ;o).
2. Yes one file per content type
3. I would simply filter projects from my data file for each relevant category. A custom filter checking if a project contains the category you are looking for would do the trick.

**Comment by alexpi** [comment]
Ok, thanks!

**Comment by jeromecoupe** [comment]
The kind of filter I would use for that: https://github.com/jeromecoupe/eleventy_starter/blob/master/src/_filters/include.js

Usage
```njk
{% set blogposts = collections.blogposts | include("data.categories", "test") %}
{% for post in blogposts %}
  <p>{{ post.data.title }}</p>
{% endfor %}
```
